version: "3.5"
services:
  
  clinica-mysql:
    image: mysql:8.0
    container_name: clinica-mysql
    working_dir: /application
    volumes:
      - .:/application
    environment:
      - MYSQL_ROOT_PASSWORD=clinica_2018
      - MYSQL_DATABASE=clinica
      - MYSQL_USER=clinica
      - MYSQL_PASSWORD=clinica
    command:
      --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    ports:
      - "2009:3306"

  webserver:
    image: nginx:alpine
    container_name: clinica-webserver
    working_dir: /application
    volumes:
      - .:/application
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "2000:80"

  clinica-php-fpm:
    build: .
    image: clinica_php_fpm:latest
    container_name: clinica-php-fpm
    working_dir: /application
    volumes:
      - .:/application